// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MottuChallenge.API.Data;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MottuChallenge.API.Migrations
{
    [DbContext(typeof(MottuDbContext))]
    partial class MottuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MottuChallenge.API.Models.Cliente", b =>
                {
                    b.Property<string>("UsuarioCliente")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DataUltimaManutencao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("MotoPlaca")
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("QuantidadeManutencoes")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR2(256)");

                    b.HasKey("UsuarioCliente");

                    b.HasIndex("MotoPlaca");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("MottuChallenge.API.Models.Funcionario", b =>
                {
                    b.Property<string>("UsuarioFuncionario")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("NomePatio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR2(256)");

                    b.HasKey("UsuarioFuncionario");

                    b.HasIndex("NomePatio");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("MottuChallenge.API.Models.Moto", b =>
                {
                    b.Property<string>("Placa")
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DataUltimaRevisao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Modelo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomePatio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("PrecisaManutencao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<float>("ProbabilidadeManutencao")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<int>("QuantidadeRevisoes")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Setor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("UsuarioFuncionario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("Placa");

                    b.HasIndex("NomePatio");

                    b.HasIndex("UsuarioFuncionario");

                    b.ToTable("Motos");
                });

            modelBuilder.Entity("MottuChallenge.API.Models.Patio", b =>
                {
                    b.Property<string>("NomePatio")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("VagasOcupadas")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("VagasTotais")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("NomePatio");

                    b.ToTable("Patios");
                });

            modelBuilder.Entity("MottuChallenge.API.Models.Cliente", b =>
                {
                    b.HasOne("MottuChallenge.API.Models.Moto", "Moto")
                        .WithMany()
                        .HasForeignKey("MotoPlaca");

                    b.Navigation("Moto");
                });

            modelBuilder.Entity("MottuChallenge.API.Models.Funcionario", b =>
                {
                    b.HasOne("MottuChallenge.API.Models.Patio", "Patio")
                        .WithMany("Funcionarios")
                        .HasForeignKey("NomePatio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("MottuChallenge.API.Models.Moto", b =>
                {
                    b.HasOne("MottuChallenge.API.Models.Patio", "Patio")
                        .WithMany("Motos")
                        .HasForeignKey("NomePatio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MottuChallenge.API.Models.Funcionario", "Funcionario")
                        .WithMany("Motos")
                        .HasForeignKey("UsuarioFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("MottuChallenge.API.Models.Funcionario", b =>
                {
                    b.Navigation("Motos");
                });

            modelBuilder.Entity("MottuChallenge.API.Models.Patio", b =>
                {
                    b.Navigation("Funcionarios");

                    b.Navigation("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
